name: "Set up Leverage AWS credentials"
description: "Setup AWS credentials using Binbash Leverage convention"

inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  aws_management_account_id:
    description: "AWS Management Account ID"
    required: false
    default: "000000000000"
  aws_security_account_id:
    description: "AWS Security Account ID"
    required: false
    default: "000000000000"
  aws_shared_account_id:
    description: "AWS Shared Account ID"
    required: true
  aws_network_account_id:
    description: "AWS Network Account ID"
    required: true
  aws_devstg_account_id:
    description: "AWS DevStg Account ID"
    required: true
  aws_prd_account_id:
    description: "AWS Prd Account ID"
    required: false
    default: "000000000000"
  aws_data_science_account_id:
    description: "AWS Data Science Account ID"
    required: false
    default: "000000000000"

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      shell: bash
      run: |
        set +x
        mkdir -p ~/.aws/bb

        cat > ~/.aws/bb/config << 'EOF'
        [profile bb-deploymaster]
        region = us-east-1
        output = json

        [profile bb-management-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_management_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster

        [profile bb-security-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_security_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster

        [profile bb-shared-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_shared_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster

        [profile bb-network-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_network_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster

        [profile bb-apps-devstg-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_devstg_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster

        [profile bb-apps-prd-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_prd_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster

        [profile bb-data-science-devops]
        output = json
        region = us-east-1
        role_arn = arn:aws:iam::${{ inputs.aws_data_science_account_id }}:role/DeployMaster
        source_profile = bb-deploymaster
        EOF

        cat > ~/.aws/bb/credentials << EOF
        [bb-deploymaster]
        aws_access_key_id = ${{ inputs.aws_access_key_id }}
        aws_secret_access_key = ${{ inputs.aws_secret_access_key }}
        region = us-east-1
        output = json
        EOF

        # Copy to standard AWS location as well
        cp ~/.aws/bb/config ~/.aws/config 2>/dev/null || true
        cp ~/.aws/bb/credentials ~/.aws/credentials 2>/dev/null || true

        echo "✅ AWS credentials configured for Leverage"
