locals {
  tags = {
    Terraform   = "true"
    Environment = var.environment
    Project     = var.project
    #Layer       = local.layer_name
  }

  # ---------------------------------------------------------------------------
  # Cluster access -- EKS access entries
  # ---------------------------------------------------------------------------
  # These replace the `aws-auth` ConfigMap. Its submodule was removed in
  # terraform-aws-eks v21, and access entries are the AWS-recommended mechanism
  # regardless: they are plain AWS API objects, so granting access no longer
  # requires reaching the (private) Kubernetes API -- which is what lets this
  # layer drop its `kubernetes` provider entirely.
  #
  # Both admins are listed explicitly here, which is why
  # `enable_cluster_creator_admin_permissions` is off in
  # `eks-workers-managed.tf`. That flag injects an extra entry keyed
  # `cluster_creator` for whoever runs the apply, and the module merges it in by
  # *map key* rather than by principal (`merged_access_entries` in the module's
  # `main.tf`). Since the identity that applies this layer IS the SSO DevOps
  # role below, leaving the flag on would produce two `aws_eks_access_entry`
  # resources for one principal and fail the apply with `ResourceInUseException`.
  # NOTE the namespace: EKS access policies are NOT IAM policies. They live under
  # `eks::aws:cluster-access-policy/`, and passing the IAM form
  # (`arn:aws:iam::aws:policy/...`) is rejected with
  # `InvalidParameterException: The policyArn parameter format is not valid`.
  eks_cluster_admin_policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"

  # The DevOps permission set's role name carries a suffix generated by IAM
  # Identity Center, and it changes whenever the permission set is recreated.
  # It used to be hardcoded here and had silently gone stale: the mapped role
  # was `AWSReservedSSO_DevOps_2b78d1d8a7818ab3` while the live one is
  # `AWSReservedSSO_DevOps_229828e5923d6952`, so that aws-auth entry had been
  # granting nothing. Resolve it instead of pinning it.
  #
  # Note the ARN is used verbatim, INCLUDING its `/aws-reserved/sso.amazonaws.com/`
  # IAM path. The `aws-auth` ConfigMap wanted SSO role ARNs with the path
  # stripped, and that convention does NOT carry over: access entries validate
  # that the principal actually exists, so the path-less form is rejected with
  # `InvalidParameterException: The specified principalArn is invalid: invalid
  # principal.` (Verified against this cluster on 2026-09-01.) EKS stores the
  # path as given -- the service-linked `AWSServiceRoleForAmazonEKS` entry it
  # creates for itself is path-ful too -- so there is no normalisation diff.
  sso_devops_role_arn = one(data.aws_iam_roles.sso_devops.arns)

  access_entries = {
    # Legacy cross-account assumable role
    devops = {
      principal_arn = "arn:aws:iam::${var.accounts.apps-devstg.id}:role/DevOps"
      policy_associations = {
        admin = {
          policy_arn   = local.eks_cluster_admin_policy_arn
          access_scope = { type = "cluster" }
        }
      }
    }
    # SSO DevOps permission set -- the identity that actually applies this layer
    sso_devops = {
      principal_arn = local.sso_devops_role_arn
      policy_associations = {
        admin = {
          policy_arn   = local.eks_cluster_admin_policy_arn
          access_scope = { type = "cluster" }
        }
      }
    }
  }

  # ---------------------------------------------------------------------------
  # Bootstrap add-ons -- must exist BEFORE the nodes
  # ---------------------------------------------------------------------------
  # v21 hardcodes `bootstrap_self_managed_addons = false` on the cluster (it is
  # no longer even a variable). v20 left it `null`, so the argument was omitted
  # and the AWS API default of `true` applied: EKS installed self-managed
  # kube-proxy, CoreDNS and VPC CNI when the cluster came up. That is what let
  # the nodes join on every previous spin, and why the separate `addons` layer
  # -- which runs two layers later, after `identities` -- could treat itself as
  # an upgrade rather than a first install.
  #
  # Under v21 that ordering deadlocks: a node cannot reach `Ready` without a
  # CNI, so the node groups block for their full create timeout and fail. So the
  # CNI is installed from here, with `before_compute = true`, which the module
  # routes to `aws_eks_addon.before_compute` -- created ahead of the node groups.
  #
  # Only the CNI lives here; kube-proxy, CoreDNS and the EBS CSI driver do not
  # gate node readiness and stay in the `addons` layer, where they get pinned
  # versions and IRSA roles. Consequently `vpc-cni` must NOT also be declared
  # there, or that layer's create fails with `ResourceInUseException`.
  #
  # No `service_account_role_arn`: the IRSA role for the CNI lives in
  # `identities`, which cannot exist yet on a fresh cluster. The CNI runs on the
  # node instance role instead, which carries `AmazonEKS_CNI_Policy` via
  # `iam_role_attach_cni_policy` below. No version pin either -- the add-on
  # resolves the default for the cluster's Kubernetes version, and the `addons`
  # layer is where versions are chosen deliberately.
  bootstrap_addons = {
    vpc-cni = {
      before_compute = true
      # `most_recent` defaults to TRUE in v21 (it was false in v20), which would
      # resolve the newest published CNI on every apply rather than the default
      # for this cluster's Kubernetes version -- unwanted drift on the one add-on
      # that has needed stepwise upgrades here in the past.
      most_recent                 = false
      resolve_conflicts_on_create = "OVERWRITE"
      resolve_conflicts_on_update = "OVERWRITE"
    }
  }

  # ---------------------------------------------------------------------------
  # Managed Node Group (MNG) defaults
  # ---------------------------------------------------------------------------
  # v21 removed `eks_managed_node_group_defaults` -- along with every other
  # `*_defaults` variable. The module now iterates `eks_managed_node_groups`
  # directly with no merge step, so shared attributes have to be repeated per
  # group. This local restores the single-source-of-truth property by hand:
  # `merge()` it into every group, and a group only needs its own value to
  # *differ* from this one.
  #
  # Nitro-only: AL2023 (see var.ami_type) needs ENA + NVMe, so Xen generations
  # like t2 are excluded -- they would be accepted by the spot allocator and
  # then fail to boot.
  #
  # NOTE: the v20 defaults block also carried `k8s_labels = local.tags`, which
  # was never a real input -- the node group submodule's key is `labels`. Under
  # v20's `any` type it was silently discarded, so those tags never landed as
  # Kubernetes labels; under v21's typed object it would be a hard error. The
  # per-group `labels` below are the ones that always worked.
  node_group_defaults = {
    ami_type       = var.ami_type
    instance_types = ["t3.medium", "t3a.medium", "m5.large", "m5a.large", "m6a.large", "m6i.large"]

    # Root volume. NOTE: this deliberately does NOT use `disk_size`, which is a
    # no-op here and had been one since 2023: the module sets
    # `disk_size = use_custom_launch_template ? null : disk_size`, and
    # `use_custom_launch_template` defaults to true, so the node group's own
    # `disk_size` is always discarded and the size has to come from the launch
    # template instead. The layer asked for 50 GiB and silently got the AL2023
    # AMI default (20 GiB) on every spin. Identical logic in v20.37.2 and
    # v21.25.0 -- this is a latent bug being fixed alongside the bump, not a
    # v21 regression.
    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs = {
          volume_size           = 50
          volume_type           = "gp3"
          encrypted             = true
          delete_on_termination = true
        }
      }
    }
    # IMPORTANT: setting this to true is only necessary during the initial bootstrap
    # of the cluster, otherwise the built-in VPC CNI won't start. Then, after you get
    # the VPC CNI add-on installed, you can set this to false.
    iam_role_attach_cni_policy = true
  }

  # ---------------------------------------------------------------------------
  # IMPORTANT
  # ---------------------------------------------------------------------------
  # If you plan to use EKS managed add-ons keep in mind that some add-ons rely
  # on IAM roles which need to be created/updated for them to work. Said roles
  # are defined in the "identities" layer which needs to be applied only after
  # the cluster is up and running. You can orchestrate that execution in that
  # order by toggling the "use_managed_addons" variable in "variables.tf".
  # Said execution order should go as follows:
  #   1. Apply this layer
  #   2. Apply the identities layers
  #   3. Enable the "use_managed_addons" variable and apply this layer again
  # ---------------------------------------------------------------------------
  addons_available = {
  }
  addons_enabled = var.use_managed_addons ? local.addons_available : {}
}
