locals {
  tags = {
    Terraform   = "true"
    Environment = var.environment
    Project     = var.project
    #Layer       = local.layer_name
  }

  # ---------------------------------------------------------------------------
  # Cluster access -- EKS access entries
  # ---------------------------------------------------------------------------
  # These replace the `aws-auth` ConfigMap. Its submodule was removed in
  # terraform-aws-eks v21, and access entries are the AWS-recommended mechanism
  # regardless: they are plain AWS API objects, so granting access no longer
  # requires reaching the (private) Kubernetes API -- which is what lets this
  # layer drop its `kubernetes` provider entirely.
  #
  # Both admins are listed explicitly here, which is why
  # `enable_cluster_creator_admin_permissions` is off in
  # `eks-workers-managed.tf`. That flag injects an extra entry keyed
  # `cluster_creator` for whoever runs the apply, and the module merges it in by
  # *map key* rather than by principal (`merged_access_entries` in the module's
  # `main.tf`). Since the identity that applies this layer IS the SSO DevOps
  # role below, leaving the flag on would produce two `aws_eks_access_entry`
  # resources for one principal and fail the apply with `ResourceInUseException`.
  # NOTE the namespace: EKS access policies are NOT IAM policies. They live under
  # `eks::aws:cluster-access-policy/`, and passing the IAM form
  # (`arn:aws:iam::aws:policy/...`) is rejected with
  # `InvalidParameterException: The policyArn parameter format is not valid`.
  eks_cluster_admin_policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"

  # The DevOps permission set's role name carries a suffix generated by IAM
  # Identity Center, and it changes whenever the permission set is recreated.
  # It used to be hardcoded here and had silently gone stale: the mapped role
  # was `AWSReservedSSO_DevOps_2b78d1d8a7818ab3` while the live one is
  # `AWSReservedSSO_DevOps_<REDACTED>`, so that aws-auth entry had been
  # granting nothing. Resolve it instead of pinning it.
  #
  # Note the ARN is used verbatim, INCLUDING its `/aws-reserved/sso.amazonaws.com/`
  # IAM path. The `aws-auth` ConfigMap wanted SSO role ARNs with the path
  # stripped, and that convention does NOT carry over: access entries validate
  # that the principal actually exists, so the path-less form is rejected with
  # `InvalidParameterException: The specified principalArn is invalid: invalid
  # principal.` (Verified against this cluster on 2026-09-01.) EKS stores the
  # path as given -- the service-linked `AWSServiceRoleForAmazonEKS` entry it
  # creates for itself is path-ful too -- so there is no normalisation diff.
  sso_devops_role_arn = one(data.aws_iam_roles.sso_devops.arns)

  access_entries = {
    # Legacy cross-account assumable role
    devops = {
      principal_arn = "arn:aws:iam::${var.accounts.apps-devstg.id}:role/DevOps"
      policy_associations = {
        admin = {
          policy_arn   = local.eks_cluster_admin_policy_arn
          access_scope = { type = "cluster" }
        }
      }
    }
    # SSO DevOps permission set -- the identity that actually applies this layer
    sso_devops = {
      principal_arn = local.sso_devops_role_arn
      policy_associations = {
        admin = {
          policy_arn   = local.eks_cluster_admin_policy_arn
          access_scope = { type = "cluster" }
        }
      }
    }
  }

  # ---------------------------------------------------------------------------
  # Bootstrap add-ons -- must exist BEFORE the nodes
  # ---------------------------------------------------------------------------
  # v21 hardcodes `bootstrap_self_managed_addons = false` on the cluster (it is
  # no longer even a variable). v20 left it `null`, so the argument was omitted
  # and the AWS API default of `true` applied: EKS installed self-managed
  # kube-proxy, CoreDNS and VPC CNI when the cluster came up. That is what let
  # the nodes join on every previous spin, and why the separate `addons` layer
  # -- which runs two layers later, after `identities` -- could treat itself as
  # an upgrade rather than a first install.
  #
  # Under v21 that ordering deadlocks: a node cannot reach `Ready` without a
  # CNI, so the node groups block for their full create timeout and fail. So the
  # CNI is installed from here, with `before_compute = true`, which the module
  # routes to `aws_eks_addon.before_compute`.
  #
  # `before_compute` buys a *head start*, not an ordering guarantee -- it is a
  # timed gap (`dataplane_wait_duration`) rather than a dependency edge. See the
  # "WHAT IS AND IS NOT ORDERED" note in `irsa-vpc-cni.tf`, and the
  # `dataplane_wait_duration` argument in `eks-workers-managed.tf`.
  #
  # Only the CNI lives here; kube-proxy, CoreDNS and the EBS CSI driver do not
  # gate node readiness and stay in the `addons` layer, where they get pinned
  # versions and IRSA roles. Consequently `vpc-cni` must NOT also be declared
  # there, or that layer's create fails with `ResourceInUseException`.
  #
  # `service_account_role_arn` points at a role created in THIS layer
  # (`irsa-vpc-cni.tf`), not in `identities` — read the comment there, it is the
  # whole reason the CNI gets its own identity instead of borrowing the node
  # role's. It is pinned, like the add-ons in the `addons` layer -- see the note
  # on `addon_version` below for why `most_recent = false` is not a pin.
  bootstrap_addons = {
    vpc-cni = {
      before_compute = true

      # Pinned, for the same reason the `addons` layer pins its own two, and it
      # has to be an explicit `addon_version` rather than `most_recent = false`.
      #
      # `most_recent` only chooses *which* version the module resolves: false
      # picks the default for this cluster's Kubernetes version instead of the
      # newest published one. It does not stop the resolution. The module writes
      # the resolved string into the resource either way --
      # `addon_version = coalesce(each.value.addon_version,
      # data.aws_eks_addon_version.this[each.key].version)` (upstream
      # `main.tf:860`) -- and that data source is re-read on every plan. AWS
      # revises the default version for a given Kubernetes version over time, so
      # without a pin the next plan after such a revision shows an add-on version
      # change and the apply upgrades the CNI in place, on whatever unrelated
      # change happens to be applied that day.
      #
      # `v1.22.4-eksbuild.3` is the current default for 1.34, so this pin is a
      # no-op today -- it only removes the ambient upgrade. Keep `most_recent`
      # false alongside it: it is what the resolution falls back to should the
      # pin ever be removed.
      addon_version               = "v1.22.4-eksbuild.3"
      most_recent                 = false
      resolve_conflicts_on_create = "OVERWRITE"
      resolve_conflicts_on_update = "OVERWRITE"
      service_account_role_arn    = module.irsa_vpc_cni.iam_role_arn
    }
  }

  # ---------------------------------------------------------------------------
  # Managed Node Group (MNG) defaults
  # ---------------------------------------------------------------------------
  # v21 removed `eks_managed_node_group_defaults` -- along with every other
  # `*_defaults` variable. The module now iterates `eks_managed_node_groups`
  # directly with no merge step, so shared attributes have to be repeated per
  # group. This local restores the single-source-of-truth property by hand:
  # `merge()` it into every group, and a group only needs its own value to
  # *differ* from this one.
  #
  # Nitro-only: AL2023 (see var.ami_type) needs ENA + NVMe, so Xen generations
  # like t2 are excluded -- they would be accepted by the spot allocator and
  # then fail to boot.
  #
  # NOTE: the v20 defaults block also carried `k8s_labels = local.tags`, which
  # was never a real input -- the node group submodule's key is `labels`. Under
  # v20's `any` type it was silently discarded, so those tags never landed as
  # Kubernetes labels; under v21's typed object it would be a hard error. The
  # per-group `labels` below are the ones that always worked.
  node_group_defaults = {
    ami_type       = var.ami_type
    instance_types = ["t3.medium", "t3a.medium", "m5.large", "m5a.large", "m6a.large", "m6i.large"]

    # Root volume. NOTE: this deliberately does NOT use `disk_size`, which is a
    # no-op here and had been one since 2023: the module sets
    # `disk_size = use_custom_launch_template ? null : disk_size`, and
    # `use_custom_launch_template` defaults to true, so the node group's own
    # `disk_size` is always discarded and the size has to come from the launch
    # template instead. The layer asked for 50 GiB and silently got the AL2023
    # AMI default (20 GiB) on every spin. Identical logic in v20.37.2 and
    # v21.25.0 -- this is a latent bug being fixed alongside the bump, not a
    # v21 regression.
    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs = {
          volume_size = 50
          volume_type = "gp3"
          # Belt-and-braces rather than the thing doing the work:
          # `apps-devstg/us-east-1/security-base` sets
          # `aws_ebs_encryption_by_default`, so these volumes are encrypted with
          # or without this line. Kept explicit because it documents the intent
          # and does not depend on another layer staying applied.
          #
          # No `kms_key_id`, so they land on the account default, which is
          # `alias/aws/ebs` -- there is no `aws_ebs_default_kms_key` in the
          # account. That differs from the control plane two blocks up, which is
          # on the account CMK, and the asymmetry is deliberate at the account
          # baseline rather than something to re-litigate here.
          encrypted             = true
          delete_on_termination = true
        }
      }
    }
    # `false` on purpose, and it is the point of `irsa-vpc-cni.tf`.
    #
    # This attaches `AmazonEKS_CNI_Policy` to the *node instance role*, which
    # means every pod that can reach the node's credentials inherits ENI and
    # subnet write permissions. AWS's own guidance is to give `aws-node` a
    # dedicated role via IRSA and then remove the policy from the node role, and
    # that is exactly what happens now: `local.bootstrap_addons.vpc-cni` carries
    # a `service_account_role_arn`, so the CNI has its own scoped credentials
    # from the moment the cluster exists.
    #
    # It was `true` for one commit, while the CNI briefly ran on the node role --
    # v21 forced the CNI to be installed before the nodes, and the role for it
    # was still stranded in the `identities` layer, which runs afterwards. Moving
    # the role into this layer removed that constraint.
    #
    # If you ever set this back to `true`, also drop the add-on's
    # `service_account_role_arn`, or you will have two credential paths and no
    # clear answer about which one `aws-node` is using.
    iam_role_attach_cni_policy = false
  }

  # `addons_available` / `addons_enabled` / `var.use_managed_addons` used to sit
  # here, described as a three-step dance for add-ons that need an IRSA role
  # from the `identities` layer: apply this layer, apply `identities`, then flip
  # the variable and apply again. It was never implemented -- `addons_available`
  # was an empty map, so `addons_enabled` was `{}` under both branches of the
  # conditional and the variable had no effect at any value. Removed rather than
  # completed, because the problem it described is gone: the one add-on that
  # needed a role before the nodes exist now gets it from `irsa-vpc-cni.tf` in
  # this layer, and everything else is declared in `addons`, which runs after
  # `identities` and can just reference it.
}
