#
# EKS Module
#
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

#
# VPC Module
#
output "vpc_id" {
  description = "VPC ID"
  value       = module.vpc-eks.vpc_id
}

output "vpc_name" {
  description = "VPC Name"
  value       = "${local.vpc_name}"
}

output "vpc_cidr_block" {
  description = "VPC CIDR Block"
  value       = "${local.vpc_cidr_block}"
}

output "availability_zones" {
  description = "List of availability zones"
  value       = ["${local.azs}"]
}

# Subnets
output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = ["${module.vpc-eks.private_subnets}"]
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = ["${module.vpc-eks.public_subnets}"]
}

output "private_subnets_cidr" {
  description = "List of IDs of private subnets"
  value       = ["${local.private_subnets}"]
}

output "public_subnets_cidr" {
  description = "List of IDs of public subnets"
  value       = ["${local.public_subnets}"]
}

output "nat_gateway_ids" {
  description = "NAT Gateway IDs"
  value       = ["${module.vpc-eks.natgw_ids}"]
}

output "public_route_table_ids" {
  description = "List of IDs of public route tables"
  value       = module.vpc-eks.public_route_table_ids
}

output "private_route_table_ids" {
  description = "List of IDs of private route tables"
  value       = module.vpc-eks.private_route_table_ids
}