define TF_IMPORT_RESOURCE_LIST
"aws_s3_bucket.gdrive_backup","bb-shared-gdrive-backup"
endef

TF_RM_RESOURCE := "aws_s3_bucket.gdrive_bakcup"

-include ../../@bin/makefiles/terraform13/terraform13-mfa.mk
-include ../../@bin/makefiles/terraform13/terraform13-import-rm.mk
