#
# EKS Module
#
output "cluster_name" {
  description = "EKS Cluster Name"
  value       = data.terraform_remote_state.vpc-eks.outputs.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

#
# SG Worker Management
#
output "sg_all_worker_mgmt_id" {
  description = "Security group for EKS Worker SSH management"
  value       = aws_security_group.all_worker_mgmt.*.id
}
