controller:
  ## DaemonSet or Deployment
  kind: DaemonSet

  ## Name of the ingress class to route through this controller
  ingressClass: ingress-nginx-public

  service:
    enabled: true

    annotations:
      # Use a Network Load Balancer (either nlb or alb)
      service.beta.kubernetes.io/aws-load-balancer-type: nlb

defaultBackend:
  enabled: true
