# Annotate the service account for EKS IRSA
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::763606934258:role/demoapps-aws-es-proxy

# AWS ElasticSearch requires using signed requests. You can configure that here:
awsSigningSidecar:
  enabled: true
  image:
    repository: abutaha/aws-es-proxy
    tag: v1.1
  extraEnvs:
  - name: AWS_ROLE_ARN
    value: "arn:aws:iam::763606934258:role/demoapps-aws-es-proxy"
  - name: AWS_WEB_IDENTITY_TOKEN_FILE
    value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"

elasticsearch:
  auth:
    enabled: false

  # Set an index prefix -- We do not really expect to talk to LogStash but the
  # chart needs to be configured like this to enable index prefixes
  logstash:
    enabled: true
    prefix: "fluentd-apps-devstg-demoapps"

  # ElasticSearch connection settings
  hosts: ["vpc-es-aws-binbash-6uuj35w6h36g66nr74omalvtji.us-east-1.es.amazonaws.com"]
  scheme: "https"
  sslVerify: true
  sslVersion: "TLSv1_2"

  # Useful for debugging
  logLevel: "info"

  # Define an index template
  template:
    enabled: true
    overwrite: false
    useLegacy: true
    name: fluentd-template
    file: fluentd-template.json
    content: |-
      {
        "index_patterns": [
            "fluentd-*"
        ],
        "settings": {
            "index": {
                "number_of_replicas": "0"
            }
        }
      }

  # Configure Index Lifecycle Management policies (not compatible as-is with AWS ES)
  # ilm:
  #   enabled: true
  #   policy_id: fluentd-policy
  #   policy:
  #     phases:
  #       hot:
  #         min_age: 0ms
  #         actions:
  #           rollover:
  #             max_age: 30d
  #             max_size: 20gb
  #           set_priority:
  #               priority: 100
  #       delete:
  #         min_age: 30d
  #         actions:
  #           delete: {}

# Toggle default configuration blocks
configMaps:
  useDefaults:
    systemConf: true
    containersInputConf: true
    containersKeepTimeKey: false
    systemInputConf: false
    forwardInputConf: false
    monitoringConf: false
    outputConf: true
