#=================#
# Layer Variables #
#=================#
variable "prefix" {
  type        = string
  description = "A prefix string to name resources. Eg ofs (object file shares)"
  default     = "ofs"
}

variable "users" {
  type = map(object({
    username       = string
    ssh_public_key = string
  }))
  description = "List of users (username and SSH public key) for which an account will be created so they can authenticate and access the server."
  default = {
    user_jane_doe = {
      username       = "jane.doe",
      ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDY0Z+dr+HTVngn/xNAtrGG6skUBwskeL1x7GvP9OLVmL3rguVMMhZVYX3etCGpzc+ZaG4eOY47phXmEzkvMHq/ls/BP0Ck4WQiU2FXMEM+O+XS9VO0Y/ARx0YwxlRgPLniO1IH/vsg1mT2mYYskHL54JXs63We1ZY6NNMuMVHllAcpnLS5HLzaE4VN9950Of8cs17/0mpz5HkkQ1UKFw40ckmyuuM14yCkixFdAAsFAQEqIBhqXKDOBuWHEoatmyHAO4GwYb14/S5VVEvHA1rIwrv6GsOunhlsUloOu+FzUKJ738p9fMaqZG6Dtsyf4pRLYFTt6tKu0tPCAKVZzf6ACTmZpVY/cxELjUHCn9NpdV6E/aMiVjfhkNQf3Fl5D2TNDbo5sfDFUg0Vqe9KIdTEqNl1rDQy5s9anOK5gzvWS/JsvPiuLTwfU1bnFWOqsdidMfk+pQf8lk5yIS61mudiS/T/U6RMz4J+SrveAB4/g2OlViLV62z+xYBjLsklWic="
    },
    user_john_doe = {
      username       = "john.doe",
      ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7KaxDBUnYwhBfNVe28HUoyxgROxY76xy98D1zOMLJDXVSwkfera00OSIlt1poHR6mp+wsT0Q8fDgJcPqSjMZzQIq7YzZfdTkWsNGC+VcT85ta8dwd/4mRyTbULl1JXQCdKdKdOZmUUeUO2U3vvUaoH1U4o3WwSHd3y5no1h+a5RVBcpoTn8tXOmtVy9LZ3rgWLxuGM9bJQ0acA39lyEV3Cz1IUdVJFJXqXyuEmoamYlvCGRHo4W5eMQVjdHbjvZInA+ArLQcQixjZ3hEcxC5xoTyzAu2bDROUBwobJIO8q7St1E312lxAz7ifvizaGlZpLADKMBpCLaT+Zt4bvsMjKxHgu9Q2CcZd3kuB7SfAJ6WBOaNUnE88CnetVsU9+PV7pRMzvCFZcjZJTgZWSNOOyPejwkOOrwJkNXbSsTJnczpvSPVvvCRBFeaTbprYb+tUT3EwY7RxtgBN/8RT9zugfgWkxYinQzX7ff7nEYW7t+LF/EKp8dPrabjOetIRd48="
    },
  }
}

variable "server_endpoint_type" {
  type        = string
  description = "The type of endpoint that you want your SFTP server connect to. Either PUBLIC or VPC."
  default     = "VPC"
}

variable "server_protocols" {
  type        = list(string)
  description = "Specifies the file transfer protocol or protocols over which your file transfer protocol client can connect to your server's endpoint."
  default     = ["SFTP"]
}

variable "server_host_key" {
  type        = string
  description = "RSA private key (e.g., as generated by the ssh-keygen -N \"\" -m PEM -f my-new-server-key command)."
  default     = null
}

variable "base_domain" {
  type        = string
  description = "Base DNS domain to create the custom endpoint of the server."
  default     = "binbash.com.ar"
}

variable "whitelisted_ips" {
  type        = list(string)
  description = "List of IP addresses that should be able to reach the server."
  default     = ["0.0.0.0/0"]
}
