"""Render findings. Pure formatting - no I/O, no AWS, no filesystem."""

from __future__ import annotations

from datetime import date

from version_support.lifecycle import BLOCKING, Finding

ISSUE_MARKER = "<!-- version-support-guardrail -->"

_SEVERITY_ICON = {
    "OK": "🟢",
    "SOON": "🟡",
    "EXTENDED": "🔴",
    "UNSUPPORTED": "🔴",
    "UNKNOWN": "⚪",
}


def _name(finding: Finding) -> str:
    pin = finding.pin
    return f"{pin.engine or 'kubernetes'} {pin.version or '?'}"


def blocking_findings(findings: list[Finding]) -> list[Finding]:
    """Findings that must fail a PR: active layers only."""
    return [f for f in findings if f.pin.active and f.severity in BLOCKING]


def attention_findings(findings: list[Finding]) -> list[Finding]:
    """Active findings worth telling a human about."""
    return [
        f for f in findings if f.pin.active and f.severity in BLOCKING | {"SOON", "UNKNOWN"}
    ]


def annotations(findings: list[Finding]) -> list[str]:
    """GitHub Actions workflow-command lines. Disabled layers never annotate."""
    lines = []
    for finding in findings:
        if not finding.pin.active:
            continue
        if finding.severity in BLOCKING:
            level = "error"
        elif finding.severity in {"SOON", "UNKNOWN"}:
            level = "warning"
        else:
            continue
        # Strip the " (how)" suffix first, then the trailing ":line" -- splitting on
        # the first colon would truncate an absolute Windows path at its drive
        # letter. Not reachable today (_source builds paths with os.path.relpath,
        # which never emits one) but a wrong file= silently points a reviewer at the
        # wrong place, so this is cheap insurance.
        file_part = finding.pin.source.split(" (")[0].rsplit(":", 1)[0]
        lines.append(
            f"::{level} file={file_part}::{_name(finding)} in {finding.pin.layer} "
            f"is {finding.severity} (end of standard support: {finding.end_standard})"
        )
    return lines


def terminal_table(findings: list[Finding]) -> str:
    """Human-readable summary for the job log."""
    active = [f for f in findings if f.pin.active]
    disabled = [f for f in findings if not f.pin.active]
    lines = ["Active layers:"]
    if not active:
        lines.append("  (none)")
    for finding in sorted(active, key=lambda f: f.pin.layer):
        lines.append(
            f"  {_SEVERITY_ICON[finding.severity]} {finding.severity:12} "
            f"{_name(finding):28} {finding.pin.layer}"
        )
        lines.append(
            f"      end of standard support: {finding.end_standard}  "
            f"days left: {finding.days_left}  source: {finding.pin.source}"
        )

    if disabled:
        lines.append("")
        lines.append("Disabled layers (latent - never fails the check):")
        for finding in sorted(disabled, key=lambda f: f.pin.layer):
            if finding.severity == "UNSUPPORTED":
                note = "past extended support -- unsupported if enabled"
            elif finding.severity == "EXTENDED":
                note = "would be in extended support if enabled"
            else:
                note = finding.severity.lower()
            lines.append(f"  · {_name(finding):28} {finding.pin.layer} - {note}")
    return "\n".join(lines)


def markdown_table(findings: list[Finding], generated_on: date) -> str:
    """The committed status table."""
    header = [
        "<!-- GENERATED by @bin/scripts/version_support - do not edit by hand -->",
        "",
        "# Version support status",
        "",
        f"Generated **{generated_on.isoformat()}**. Regenerate with `make version-support-table`.",
        "",
        "| Layer | Kind | Engine | Version | Status | End of standard support | Days left |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    rows = []
    for finding in sorted(findings, key=lambda f: (not f.pin.active, f.pin.layer)):
        pin = finding.pin
        layer = pin.layer if pin.active else f"{pin.layer} _(disabled)_"
        rows.append(
            f"| {layer} | {pin.kind} | {pin.engine or 'kubernetes'} | {pin.version or '?'} "
            f"| {_SEVERITY_ICON[finding.severity]} {finding.severity} "
            f"| {finding.end_standard or '-'} | {finding.days_left if finding.days_left is not None else '-'} |"
        )
    return "\n".join(header + rows) + "\n"


def slack_summary(findings: list[Finding]) -> str:
    """One-paragraph mrkdwn summary for the weekly notification."""
    extended = [f for f in findings if f.pin.active and f.severity == "EXTENDED"]
    unsupported = [f for f in findings if f.pin.active and f.severity == "UNSUPPORTED"]
    soon = [f for f in findings if f.pin.active and f.severity == "SOON"]
    unknown = [f for f in findings if f.pin.active and f.severity == "UNKNOWN"]
    parts = []
    if unsupported:
        # Worse than extended support: past the paid window entirely. Only shown
        # when non-empty so the common case stays a two-part summary.
        parts.append(f"*{len(unsupported)} unsupported*")
    parts.extend([
        f"*{len(extended)} in extended support*" if extended else "0 in extended support",
        f"*{len(soon)} within the lead time*" if soon else "0 within the lead time",
    ])
    if unknown:
        # attention_findings() counts UNKNOWN, so a lone UNKNOWN can be the sole
        # reason this notification fired. Without this the message would say
        # "0 in extended support - 0 within the lead time" and list nothing at all.
        parts.append(f"*{len(unknown)} could not be checked*")
    detail = "\n".join(
        f"• {_name(f)} — `{f.pin.layer}` — end of standard support {f.end_standard}"
        for f in unsupported + extended + soon + unknown
    )
    return " · ".join(parts) + ("\n" + detail if detail else "")


def slack_payload(findings: list[Finding], *, repository: str, run_url: str) -> dict:
    """Full incoming-webhook payload, written to a file the workflow posts verbatim.

    Building the whole payload here keeps multi-line summary text out of inline
    YAML, where embedded newlines would produce invalid JSON.
    """
    return {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "Version support: action needed :hourglass_flowing_sand:",
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": (
                        f"*Project*: {repository}\n"
                        f"{slack_summary(findings)}\n\n"
                        "Extended support bills at a multiple of the standard rate."
                    ),
                },
                "accessory": {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": ":arrow_forward: View run",
                        "emoji": True,
                    },
                    "url": run_url,
                    "action_id": "button-action",
                },
            },
        ]
    }


def issue_body(findings: list[Finding], generated_on: date) -> str:
    """Body for the recurring tracking issue, carrying the dedupe marker."""
    return "\n".join(
        [
            ISSUE_MARKER,
            "",
            "Versions approaching or past their end of standard support. "
            "Extended support bills at a multiple of the standard rate — "
            "the cheapest fix is the early one.",
            "",
            markdown_table(findings, generated_on),
            "",
            "_Opened and updated automatically by "
            "`.github/workflows/version-support.yml`._",
        ]
    )
