/*
* Copyright Amazon.com and its affiliates; all rights reserved.
* SPDX-License-Identifier: LicenseRef-.amazon.com.-AmznSL-1.0
* Licensed under the Amazon Software License  https://aws.amazon.com/asl/
*/

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8e9f6b16-f24a-481d-a78f-bd640d32ec7b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_YWLF1KO9O",
    "aws_user_pools_web_client_id": "7lftcfu06dfnt57lv8p8slv180",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "document_processing_input_bucket": "binbashworkshop-documentproces-inputbucket3bf8630a-vhkj4zd1lxa2",
    "kyb_api_endpoint": "https://h832letqs8.execute-api.us-west-2.amazonaws.com/prod" // Replace with your API Gateway URL
};


export default awsmobile;
