# Annotate the service account for EKS IRSA
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${roleArn}

# AWS ElasticSearch requires using signed requests. You can configure that here:
awsSigningSidecar:
  enabled: true
  image:
    repository: abutaha/aws-es-proxy
    tag: v1.1
  extraEnvs:
  - name: AWS_ROLE_ARN
    value: ${roleArn}
  - name: AWS_WEB_IDENTITY_TOKEN_FILE
    value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"

elasticsearch:
  auth:
    enabled: false

  # Set an index prefix -- We do not really expect to talk to LogStash but the
  # chart needs to be configured like this to enable index prefixes
  logstash:
    enabled: true
    prefix: "fluentd-apps-devstg-demoapps"

  # ElasticSearch connection settings
  hosts: ["vpc-es-aws-binbash-6uuj35w6h36g66nr74omalvtji.us-east-1.es.amazonaws.com:443"]
  scheme: "https"
  sslVerify: true
  sslVersion: "TLSv1_2"

  # Useful for debugging
  logLevel: "info"

  # Define an index template
  template:
    enabled: true
    overwrite: false
    useLegacy: true
    name: fluentd-template
    file: fluentd-template.json
    content: |-
      {
        "index_patterns": [
            "fluentd-*"
        ],
        "settings": {
            "index": {
                "number_of_replicas": "0"
            }
        }
      }

# Toggle default configuration blocks
configMaps:
  useDefaults:
    systemConf: true
    containersInputConf: true
    containersKeepTimeKey: false
    systemInputConf: false
    forwardInputConf: false
    monitoringConf: false
    outputConf: true
