openapi: 3.0.0
info:
  title: S3 Read API
  version: 1.0.0
paths:
  /read:
    get:
      description: Read file from S3
      operationId: readS3File
      parameters:
        - name: key
          in: query
          required: true
          description: S3 object key (supports paths with slashes)
          schema:
            type: string
      responses:
        "200":
          description: File content
          content:
            application/json:
              schema:
                type: string