openapi: 3.0.0
info:
  title: S3 Write API
  version: 1.0.0
paths:
  /write/{key}:
    post:
      description: Write content to S3
      operationId: writeS3File
      parameters:
        - name: key
          in: path
          required: true
          description: S3 object key
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Content to write to the file
              required:
                - content
      responses:
        "200":
          description: File written successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  key:
                    type: string
