name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # Only run on SSO layer changes for AI-driven analysis
    paths:
      - "management/global/sso/**"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for Claude to make code changes
      pull-requests: write  # Required for Claude to comment and create PRs
      issues: write  # Required for Claude to comment on issues
      id-token: write
      actions: read  # Required for Claude to read CI results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review with Intelligent Agent Routing
        id: claude-review
        uses: anthropics/claude-code-action@v1.0.0
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            ## AI-DRIVEN PR ANALYSIS FOR SSO LAYER

            You are Claude Code performing AI-driven analysis of pull requests affecting the SSO layer (management/global/sso/).

            **IMPORTANT**: This workflow performs ONLY static AI analysis. DO NOT execute any infrastructure commands like `leverage tofu plan`.
            Infrastructure testing is handled by a separate workflow.

            ### STEP 1: ANALYZE PR CONTEXT
            Examine this Pull Request and identify:
            - **Files changed**: Look at file paths and directories in management/global/sso/
            - **SSO configuration changes**: Permission sets, assignments, policies
            - **Security implications**: IAM changes, access control modifications
            - **Keywords**: In PR title, description, and file contents
            - **Change type**: New feature, bug fix, documentation, dependency update, etc.

            ### STEP 2: SELECT SPECIALIZED AGENT
            Based on your analysis, choose the most appropriate agent for SSO-related changes:

            - **security-compliance**: SSO permission sets, IAM policies, access control, security configurations (PREFERRED for SSO changes)
            - **terraform-layer**: General .tf file changes, resource definitions, module configurations
            - **feature-implementation**: New SSO features, permission sets, group assignments
            - **issue-fix**: Bug fixes, access issues, configuration errors
            - **documentation**: .md files, README, deployment guides
            - **dependency-update**: Module version updates, provider updates

            ### STEP 3: DELEGATE TO SPECIALIZED AGENT
            Use the Task tool to delegate the PR review to your selected agent:

            ```
            Task tool with subagent_type: [selected-agent]
            prompt: "Please review this SSO layer pull request with your specialized expertise. Focus on:
            - **Security implications**: IAM permissions, access control, least privilege principle
            - **SSO best practices**: Permission set design, group assignments, session duration
            - **Code quality**: OpenTofu/Terraform best practices, variable usage, module structure
            - **Compliance**: Adherence to Leverage Reference Architecture patterns
            - **Documentation**: Clear comments, deployment notes, breaking changes
            - **Integration considerations**: Cross-account access, dependent services

            **IMPORTANT**: This is STATIC ANALYSIS ONLY. Do NOT execute any infrastructure commands.

            Use the repository's CLAUDE.md for guidance on conventions. Be constructive and provide specific, actionable feedback.

            When complete, use 'gh pr comment' with your Bash tool to post your review as a comment on the PR."
            ```

            ### STEP 4: PROVIDE REASONING
            Briefly explain why you selected that specific agent based on your context analysis.

            ### AGENT SELECTION EXAMPLES
            - SSO permission set changes → Use `security-compliance`
            - General SSO .tf file updates → Use `terraform-layer`
            - New SSO groups or roles → Use `feature-implementation`
            - SSO configuration fixes → Use `issue-fix`
            - SSO documentation updates → Use `documentation`

            Begin with context analysis, then select and delegate to the appropriate specialized agent.

          # Configure Claude with advanced options for infrastructure review
          claude_args: |
            --max-turns 15
            --allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*),Bash(git:*),Bash(find:*),Bash(grep:*),Bash(cat:*),Bash(ls:*)"
