name: Test static code and linting
on:
  push:
    branches-ignore:
      - master
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    env:
      TF_ROOT: . #/home/runner/work/le-tf-infra-aws/le-tf-infra-aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Context Info
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -la

      - name: Initialize Repo Makefiles
        run: |
          make init-makefiles
          git update-index --assume-unchanged "Makefile"

      - name: Test dependencies
        env:
          TERRAFORM_VER_REF_ARCH: 1.1.9 #TODO:add env var
        run: |
          # Install pre-commit
          sudo -H pip3 install pre-commit
          #
          # Install terraform
          sudo apt-get install unzip curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VER_REF_ARCH}/terraform_${TERRAFORM_VER_REF_ARCH}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VER_REF_ARCH}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
          #
          # Install terraform-docs
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv ./terraform-docs /usr/local/bin/terraform-docs
          terraform-docs --version

      - name: Test terraform format and docs
        run: make pre-commit

      #is it necessary to configure aws credentials?

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-to-assume: ${{ vars.role_to_assume_in_test_and_lint_code }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DIRECT_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Failed Pipeline! :rotating_light::fire::bash-fire::bangbang::video-games-doom-mad::stopp:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":negative_squared_cross_mark: *Project*: $CIRCLE_PROJECT_REPONAME \n :negative_squared_cross_mark: *User*: $CIRCLE_USERNAME \n :negative_squared_cross_mark: *Job*: $CIRCLE_JOB in *repo* $CIRCLE_PROJECT_REPONAME \n :negative_squared_cross_mark: *Branch:* $CIRCLE_BRANCH \n :negative_squared_cross_mark: *PR:* $CIRCLE_PULL_REQUEST \n :negative_squared_cross_mark: *Last Commit:* $CIRCLE_SHA1"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":arrow_forward: View Job in CircleCi",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "$CIRCLE_BUILD_URL",
                    "action_id": "button-action"
                  }
                }
              ]
            }
